################################
# mesh configuration
################################
grid = 256, 256, 256
boundary_types = periodic, periodic, periodic, periodic, periodic, periodic

################################
# physical parameters
################################
viscosity = 0.016
gravity =    0.0, -0.1, -9.8
ambient_force =    0.0, 0.0, 0.0

################################
# timestep control
################################
istep0 = 1
nsteps = 1000
restart = false
nrestart = -1

################################
# output control
################################
noutput3 = 1000
noutput2 = 200
ndump = 2000

################################
# flow statistics control
################################
ndiag = 100
nstat = 200

################################
# device configuration
################################
gpus_per_thread = 1

################################
# turbulence parameters
################################
perturb = false
